apiVersion: v1
kind: Service
metadata:
  name: winning-number-service
spec:
  type: NodePort
  selector:
    app: winning-number
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30080
